<form id="poll-form" method="post">
	<ul class="poll-answers">
	<?php $answerCounter = 0; ?>
	<?php foreach ($answers as $answer) : ?>

		<?php
		$answerClasses = 'answer';
		if ($answerCounter % 2 == 0) {
			$answerClasses .= ' ';
			$answerClasses .= 'even';
		} else {
			$answerClasses .= ' ';
			$answerClasses .= 'odd';
		};
		if ($answerCounter == 0) {
			$answerClasses .= ' ';
			$answerClasses .= 'first';
		};
		if ($answerCounter == count($answers)) {
			$answerClasses .= ' ';
			$answerClasses .= 'last';
		};
		?>
			<li class="<?= $answerClasses ?>">
				<input type="radio" name="vote" class="radio poll_vote" id="vote_<?= $answerCounter ?>" value="<?= $answer->getAnswerId(); ?>">
				<span class="label">
					<label for="vote_<?= $answerCounter ?>"><?= $answer->getTitle(); ?></label>
				</span>
			</li>
		<?php $answerCounter++; ?>
	<?php endforeach; // end foreach $answers ?>
	</ul>
	<div class="actions">
		<input type="submit" value="<?= __('Submit') ?>">
	</div>
</form>